### ISSUE TITLE
Looks like there is a dependency on knife-ec2

### ISSUE THREAD

**Issue by rberger** [makern/knife-vagrant2#3]
I noticed that if I didn't have the knife-ec2 gem installed, knife-vagrant2 will fail when run.
Problem is solved if I install the knife-ec2 gem before running knife vagrant commands. So probably just need to add that to the readme to install knife-ec2 as well as chef and knife-vagrant2

For instance, without having knife-ec2 installed I get:

```
knife vagrant server --help
/Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/knife-vagrant2-0.0.2/lib/chef/knife/vagrant_server_delete.rb:1:in `require': cannot load such file -- chef/knife/ec2_base (LoadError)
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/knife-vagrant2-0.0.2/lib/chef/knife/vagrant_server_delete.rb:1:in `<top (required)>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/lib/chef/knife/core/subcommand_loader.rb:34:in `load'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/lib/chef/knife/core/subcommand_loader.rb:34:in `block in load_commands'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/lib/chef/knife/core/subcommand_loader.rb:34:in `each'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/lib/chef/knife/core/subcommand_loader.rb:34:in `load_commands'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/lib/chef/knife.rb:120:in `load_commands'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/lib/chef/knife.rb:168:in `run'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/lib/chef/application/knife.rb:133:in `run'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/gems/chef-11.8.2/bin/knife:25:in `<top (required)>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/bin/knife:23:in `load'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/bin/knife:23:in `<main>'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/bin/ruby_executable_hooks:15:in `eval'
    from /Users/rberger/.rvm/gems/ruby-1.9.3-p484@chef_fundamentals/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by makern** [comment]
Actually this is an oversight, there should be no dependency on knife-ec2. I will fix this and release a new version together with your other changes. Thanks a lot for your contribution!
